Blacklist-World:
  - example1
  - world2
VERSION: 1.0-B7
Vanilla_Drops: true
Tool_Sensitive: false
Auto:
  Smell: false
  Pickup: true
Number_Format: '#.###'
Input:
  # AGAIN
  Type: ONE
  Cancel_Character:
    - cancel
    - stop
Boolean:
  'true': 'On'
  'false': 'Off'
Blocks:
  COAL_ORE:
    Name: '&8Coal'
    Price: 25
    Convert: COAL
    Block: COAL_ORE
  IRON_ORE:
    Name: '&fIron Ingot'
    Price: 50
    Convert: IRON_INGOT
    Block: IRON_ORE
  GOLD_ORE:
    Name: '&eGold Ingot'
    Price: 100
    Convert: GOLD_INGOT
    Block: GOLD_ORE
  LAPIS_ORE:
    Name: '&9Lapis Lazuli'
    Price: 150
    Convert: LAPIS_LAZULI
    Block: LAPIS_ORE
  REDSTONE_ORE:
    Name: '&cRedstone'
    Price: 200
    Type: Ore
    Convert: REDSTONE
    Block: REDSTONE_ORE
  DIAMOND_ORE:
    Name: '&bDiamond'
    Price: 250
    Convert: DIAMOND
    Block: DIAMOND_ORE
  EMERALD_ORE:
    Name: '&aEmerald'
    Price: 300
    Convert: EMERALD
    Block: EMERALD_ORE
  COAL_BLOCK:
    Name: '&8Coal Block'
    Price: 250
    Convert: COAL_BLOCK
    Block: COAL_BLOCK
  IRON_BLOCK:
    Name: '&fIron Block'
    Price: 500
    Convert: IRON_BLOCK
    Block: IRON_BLOCK
  GOLD_BLOCK:
    Name: '&eGold BLock'
    Price: 1000
    Convert: GOLD_BLOCK
    Block: GOLD_BLOCK
  LAPIS_BLOCK:
    Name: '&9Lapis Block'
    Price: 1500
    Convert: LAPIS_BLOCK
    Block: LAPIS_BLOCK
  REDSTONE_BLOCK:
    Name: '&cRedstone Block'
    Price: 2000
    Convert: REDSTONE_BLOCK
    Block: REDSTONE_BLOCK
  DIAMOND_BLOCK:
    Name: '&bDiamond BLock'
    Price: 2500
    Convert: DIAMOND_BLOCK
    Block: DIAMOND_BLOCK
  EMERALD_BLOCK:
    Name: '&aEmerald'
    Price: 3000
    Convert: EMERALD_BLOCK
    Block: EMERALD_BLOCK
  STONE:
    Name: '&7Stone'
    Price: 10
    Convert: STONE
    Block: COBBLESTONE
  NETHERRACK:
    Name: '&3Netherrack'
    Price: 15
  END_STONE:
    Name: '&dEnd Stone'
    Price: 20
  WHITE_STAINED_GLASS:
    Name: '&fWhite Glass'
    Price: 30
  YELLOW_STAINED_GLASS:
    Name: '&eYellow Glass'
    Price: 30
Default_Max_Storage: 10000
Fortune:
  # True for vanilla fortune / False for custom fortune
  Vanilla: true
  # The chance * enchantment level is the real chance in system
  # Chance per level to apply custom fortune when player break block
  Chance: 10
  Drop:
    # Minimum item can drop if fortune applied
    Min: 1
    # Maximum item can drop if fortune applied
    Max: 5
Message:
  TAKE:
    # ACTION_BAR / CHAT / TITLE
    TYPE: CHAT
    # true or false
    STATUS: true
    TITLE:
      TITLE: '&cTake %item% x%amount%&c from Storage'
      SUBTITLE: '&a(%storage%/%max%)'
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  REMOVE:
    # ACTION_BAR / CHAT / TITLE
    TYPE: ACTION_BAR
    # true or false
    STATUS: true
    TITLE:
      TITLE: '&c-%amount% %item%'
      SUBTITLE: '&a(%storage%/%max%)'
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  ADD:
    # ACTION_BAR / CHAT / TITLE
    TYPE: CHAT
    # true or false
    STATUS: true
    TITLE:
      TITLE: '&aAdd %item% &7(x%amount%)&a to Storage'
      SUBTITLE: '&a(%storage%/%max%)'
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  RECEIVE:
    # ACTION_BAR / CHAT / TITLE
    TYPE: ACTION_BAR
    # true or false
    STATUS: true
    TITLE:
      TITLE: '&a+%amount% %item%'
      SUBTITLE: '&a(%storage%/%max%)'
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  SELL:
    # ACTION_BAR / CHAT / TITLE
    TYPE: ACTION_BAR
    # true or false
    STATUS: true
    TITLE:
      TITLE: '&eSold %amount% x%item%'
      SUBTITLE: '&a+ %money% &d| &b(%storage%/%max%)'
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  FULL:
    # ACTION_BAR / CHAT / TITLE
    TYPE: TITLE
    TITLE:
      TITLE: '&cWarning'
      SUBTITLE: '&c%item%&6 storage has reached its limit'
      FADEIN: 30
      FADEOUT: 10
      STAY: 20
  TOGGLE:
    # ACTION_BAR / CHAT
    TYPE: CHAT
    # true or false
    STATUS: true