name: Storage
version: '${project.version}'
main: net.danh.storage.Storage
authors: [ VoChiDanh ]
api-version: 1.13
website: https://vochidanh.gitbook.io/storage/
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  Storage:
    aliases:
      - store
      - kho
    description: Storage Commands
  AutoPickup:
    aliases: [ ap ]
    description: Toggle Pickup
  AutoSmelt:
    aliases: [ as ]
    description: Toggle Smelt
